### ISSUE TITLE
Better suggestions in VSCode chat

### ISSUE THREAD

**Issue by k12teach** [chep/copilot-chat.el#24]
I am not sure if this is normal difference because of the nature of AI, but I find the suggestions based on a single file and a directed question produces better results in VSCode over copilot-chat. Here is the sample buffer attached in both VSCode and Emacs (copilot-chat-add-current-buffer) 

```yaml
---
question:
  - text: Which of the following is not an assignment operator?
  - code:
      - '**='
      - '/='
      - '=='
      - '%='
answer:
  - code: ==
tags:
  - basics
  - operators
exam: None
book: None
---
question:
  - text: Which of the following is valid logical operator
  - code:
      - '&&'
      - '>'
      - 'and'
      - '=='
answer:
  - text: and
tags:
  - basics
  - operators
exam: None
book: None
```

Here is the sample prompt given to Emacs and VSCode 

```
Convert the following questions to yaml format strictly following the example.yml file attached. Include answers, tags and marks for each question. 

1. Which of the following commands will create a list?
2. list1 = list()
3. list1 = []
4. list1 = list([1, 2, 3])
5. all of the mentioned
```

The response returned in Emacs is 

```yaml
questions:
  - question: "Which of the following commands will create a list?"
    options:
      - "list1 = list()"
      - "list1 = []"
      - "list1 = list([1, 2, 3])"
      - "all of the mentioned"
    answer: "all of the mentioned"
    tags: ["list", "creation"]
    marks: 1
```

The response returned in VSCode is 
```yaml
---
question:
  - text: Which of the following commands will create a list?
  - options:
      - code: 'list1 = list()'
      - code: 'list1 = []'
      - code: 'list1 = list([1, 2, 3])'
      - code: 'all of the mentioned'
answer:
  - code: 'all of the mentioned'
tags:
  - lists
  - creation
marks: 1
```

The example.yml file contains 55 questions, and the prompt contains 15 questions. Only a sample is attached above. I have similar results with most responses based on attached buffers in Emacs.
